services:
  - type: web
    name: ff-update-backend
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
